### ISSUE TITLE
[wifi_iot] Android PeerToPeer API will not allow us to use the internal lan.

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutternetwork/WiFiFlutter#247]
`        connectivityManager.bindProcessToNetwork(network)`

Is missing in the onAvailable callback for connectTo on android Q and above. 

https://stackoverflow.com/questions/56831023/android-q-programmatically-connect-to-different-wifi-ap-for-internet

**Comment by daadu** [comment]
It is not added deliberately and left up to user to enable and disable it with `forceWifiUsage(true)` API

**Comment by seikosantana** [comment]
thanks @daadu 
It works for me but how do we use `forceWifiUsage(true)` correctly?
I've tried it and got it working to reach LAN but then sometimes when I'm trying to perform network operations it throws exception saying `[SocketException: Connection failed (OS Error: Machine is not on the network, errno = 64)](https://stackoverflow.com/questions/71510645/socketexception-connection-failed-os-error-machine-is-not-on-the-network-err)`. I'm suspecting that that foreWifiUsage could be the cause.

Is it supposed to be invoked only after a successful connection? How do I reset the behavior so that user can connect to WiFi normally after?

**Comment by daadu** [comment]
You can disable these behaviour with `forceWifiUsage(false)`, also on some device vendors it can behave weird, therefore you can also try `disconnect`

**Comment by seikosantana** [comment]
Noted, thanks a lot
