### ISSUE TITLE
[wifi_scan] feature request: absolute timestamp

### ISSUE THREAD

**Issue by solsticedhiver** [flutternetwork/WiFiFlutter#337]
the WifiAccessPoint returned by getSacnnedResults and other method has a timestamp field that is:

   Timestamp in microseconds (since boot) when this result was last seen.

This is not really easy to deal with. Then, you have to get the uptime of the device and add it to the given timestamp.

And this is not accurate, because from the time you get the access points results, and you query the uptime, some delay might have happened.

It would be easier (for me at least), to get a Datetime in UTC or something like that i.e. an absolute time, not a relative, from one that is constantly shifting.

**Comment by carterbox** [comment]
It looks like the decision to use "time since boot" instead of epoch time comes directly from the Android API, so maybe it's out of the scope of this package to do the conversion. That might be misleading due to the overhead you have mentioned.

https://developer.android.com/reference/android/net/wifi/ScanResult#timestamp
